//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpLauncher.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpLauncher.Gui.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string de_AudioLabel {
            get {
                return ResourceManager.GetString("de_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streichung.
        /// </summary>
        internal static string de_Cancel {
            get {
                return ResourceManager.GetString("de_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung der Dateien, bitte warten….
        /// </summary>
        internal static string de_CheckingFiles {
            get {
                return ResourceManager.GetString("de_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung Netzwerk, bitte warten….
        /// </summary>
        internal static string de_CheckingNetwork {
            get {
                return ResourceManager.GetString("de_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        internal static string de_ConfigMenu {
            get {
                return ResourceManager.GetString("de_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler trat beim patchen auf.
        ///Bitte starten sie das Update erneut.
        ///
        ///Sollte das Problem weiterhin bestehen, wenden sie sich bitte an Ataris&apos; technischen Kundendienst..
        /// </summary>
        internal static string de_Error {
            get {
                return ResourceManager.GetString("de_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht genügend Platz auf &quot;{0}&quot; vorhanden um ein Update zu installieren.
        ///Das Update benötigt {1} freien Speicher.
        /// </summary>
        internal static string de_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("de_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es kam zu einem Fehler beim Download.
        ///Überprüfen sie ihre Internetverbindung und starten sie das Update erneut.
        ///
        ///Sollte das Problem fortbestehen, wenden sie sich bitte an Ataris&apos; technischen Kundendienst..
        /// </summary>
        internal static string de_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("de_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Spiel konnte nicht wie vorgesehen installiert werden.
        ///Bitte installieren sie das Spiel erneut (über die DVD oder den heruntergeladenen Installer).
        ///
        ///Sollte das Problem fortbestehen, wenden sie sich bitte an Ataris&apos; technischen Kundendienst..
        /// </summary>
        internal static string de_ErrorGameInstall {
            get {
                return ResourceManager.GetString("de_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde ein Fehler bei der Installation festgestellt.
        ///Bitte überprüfen sie ihre Zugriffsrechte im Verzeichnis &quot;{0}&quot; und starten sie das Update erneut.
        ///
        ///Sollte das Problem fortbestehen, wenden sie sich bitte an Ataris&apos; technischen Kundendienst..
        /// </summary>
        internal static string de_ErrorInstallFile {
            get {
                return ResourceManager.GetString("de_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger CD-Key.
        /// </summary>
        internal static string de_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("de_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr System erfüllt nicht die Mindestanforderungen.
        ///
        ///Mindestanforderungen:
        ///- {0} Speicher (RAM)
        ///- DirectX 9c-Grafikgerät mit WDDM, {1} Grafikspeicher (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Ihr System:
        ///- {2} Speicher (RAM)
        ///- {3} Grafikspeicher (VRAM).
        /// </summary>
        internal static string de_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("de_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritischer Fehler aufgetreten. 
        ///
        ///Sollten Sie diesen Fehler zum ersten Mal sehen, starten Sie bitte neu; ansonsten bitten wir um eine Neuinstallation..
        /// </summary>
        internal static string de_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("de_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlassen.
        /// </summary>
        internal static string de_ExitMenu {
            get {
                return ResourceManager.GetString("de_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieleserver nicht verfügbar..
        /// </summary>
        internal static string de_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("de_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieleserver verfügbar..
        /// </summary>
        internal static string de_GameServersStatusOk {
            get {
                return ResourceManager.GetString("de_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        internal static string de_Menu {
            get {
                return ResourceManager.GetString("de_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein NAT ist: .
        /// </summary>
        internal static string de_NatType {
            get {
                return ResourceManager.GetString("de_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string de_No {
            get {
                return ResourceManager.GetString("de_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiel-Update nicht möglich. 
        ///
        ///Das Spiel kann nicht mehr Online gespielt werden. 
        ///
        ///Sollten Sie ein Offline-Profil anlegen und das Spiel dadurch Patchen, können Sie später nicht mehr mit diesem Profil online spielen. 
        ///
        ///Möchten Sie Offline spielen?.
        /// </summary>
        internal static string de_OfflineMode {
            get {
                return ResourceManager.GetString("de_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string de_OK {
            get {
                return ResourceManager.GetString("de_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholung.
        /// </summary>
        internal static string de_Retry {
            get {
                return ResourceManager.GetString("de_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string de_SaveConfig {
            get {
                return ResourceManager.GetString("de_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string de_UnitBytes {
            get {
                return ResourceManager.GetString("de_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string de_UnitGigaBytes {
            get {
                return ResourceManager.GetString("de_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string de_UnitKiloBytes {
            get {
                return ResourceManager.GetString("de_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string de_UnitMegaBytes {
            get {
                return ResourceManager.GetString("de_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string de_UnitTeraBytes {
            get {
                return ResourceManager.GetString("de_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten….
        /// </summary>
        internal static string de_Wait {
            get {
                return ResourceManager.GetString("de_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string de_Yes {
            get {
                return ResourceManager.GetString("de_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string en_AudioLabel {
            get {
                return ResourceManager.GetString("en_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string en_Cancel {
            get {
                return ResourceManager.GetString("en_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking files, please wait....
        /// </summary>
        internal static string en_CheckingFiles {
            get {
                return ResourceManager.GetString("en_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking network, please wait....
        /// </summary>
        internal static string en_CheckingNetwork {
            get {
                return ResourceManager.GetString("en_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string en_ConfigMenu {
            get {
                return ResourceManager.GetString("en_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating.
        ///Please restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string en_Error {
            get {
                return ResourceManager.GetString("en_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space on &quot;{0}&quot; to install the update.
        ///The update requires {1} more available space..
        /// </summary>
        internal static string en_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("en_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading files.
        ///Please check your Internet connection and restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string en_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("en_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game did not properly install on this system.
        ///Please try to install the game again using the installer (DVD or downloaded installer).
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string en_ErrorGameInstall {
            get {
                return ResourceManager.GetString("en_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing components.
        ///Please check your permissions to access files on the directory &quot;{0}&quot;, then restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string en_ErrorInstallFile {
            get {
                return ResourceManager.GetString("en_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CDKey.
        /// </summary>
        internal static string en_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("en_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system does not meet the minimum requirements.
        ///
        ///Minimum Requirements:
        ///- {0} of system memory (RAM)
        ///- DirectX 9c graphics device with WDDM, {1} of video memory (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Your system:
        ///- {2} of system memory (RAM)
        ///- {3} of video memory (VRAM).
        /// </summary>
        internal static string en_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("en_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred. 
        ///
        ///If you are seeing this message for the first time please relaunch this application, otherwise reinstall the game..
        /// </summary>
        internal static string en_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("en_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_ExitMenu {
            get {
                return ResourceManager.GetString("en_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game servers unavailable..
        /// </summary>
        internal static string en_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("en_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game servers available..
        /// </summary>
        internal static string en_GameServersStatusOk {
            get {
                return ResourceManager.GetString("en_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string en_Menu {
            get {
                return ResourceManager.GetString("en_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your NAT type is: .
        /// </summary>
        internal static string en_NatType {
            get {
                return ResourceManager.GetString("en_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string en_No {
            get {
                return ResourceManager.GetString("en_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the game. 
        ///
        ///You won&apos;t be able to play the game online. 
        ///
        ///If you create an offline profile and update the game later you won&apos;t be able to play online with this profile. 
        ///
        ///Do you want to play offline?.
        /// </summary>
        internal static string en_OfflineMode {
            get {
                return ResourceManager.GetString("en_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string en_OK {
            get {
                return ResourceManager.GetString("en_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string en_Retry {
            get {
                return ResourceManager.GetString("en_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string en_SaveConfig {
            get {
                return ResourceManager.GetString("en_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string en_UnitBytes {
            get {
                return ResourceManager.GetString("en_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string en_UnitGigaBytes {
            get {
                return ResourceManager.GetString("en_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string en_UnitKiloBytes {
            get {
                return ResourceManager.GetString("en_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string en_UnitMegaBytes {
            get {
                return ResourceManager.GetString("en_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string en_UnitTeraBytes {
            get {
                return ResourceManager.GetString("en_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string en_Wait {
            get {
                return ResourceManager.GetString("en_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string en_Yes {
            get {
                return ResourceManager.GetString("en_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonido.
        /// </summary>
        internal static string es_AudioLabel {
            get {
                return ResourceManager.GetString("es_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string es_Cancel {
            get {
                return ResourceManager.GetString("es_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobación los archivos, por favor espere ....
        /// </summary>
        internal static string es_CheckingFiles {
            get {
                return ResourceManager.GetString("es_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobación de la red, por favor espere ....
        /// </summary>
        internal static string es_CheckingNetwork {
            get {
                return ResourceManager.GetString("es_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string es_ConfigMenu {
            get {
                return ResourceManager.GetString("es_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores se produjeron durante la actualización.
        ///Por favor, reactivar la actualización.
        ///
        ///Si el problema persiste, contactar el apoyo técnico de Atari..
        /// </summary>
        internal static string es_Error {
            get {
                return ResourceManager.GetString("es_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficiente espacio en &quot;{0}&quot; para instalar  la actualización.
        ///La actualización requiere {1} de espacio libre suplementario..
        /// </summary>
        internal static string es_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("es_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores se produjeron durante el cobro a distancia de ficheros.
        ///Comprobar la conexión a internet y reactivar la actualización
        ///
        ///Si el problema persiste, contactar el apoyo técnico de Atari..
        /// </summary>
        internal static string es_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("es_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El juego no esta instalado correctamente sobre este sistema.
        ///Intentar instalar el juego otra vez usando el instalador  (DVD o instalador descargado).
        ///
        ///Si el problema persiste, contactar el apoyo técnico de Atari..
        /// </summary>
        internal static string es_ErrorGameInstall {
            get {
                return ResourceManager.GetString("es_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores se produjeron en la instalación de los componentes.
        ///Por favor comprobar sus permisos de aceso al directorio &quot;{0}&quot;, entonces iniciar la actualización.
        ///
        ///Si el problema persiste, contactar el apoyo técnico de Atari..
        /// </summary>
        internal static string es_ErrorInstallFile {
            get {
                return ResourceManager.GetString("es_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de CD no válida.
        /// </summary>
        internal static string es_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("es_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuestro sistema no cumple los requisitos mínimos.
        ///
        ///Requisitos mínimos:
        ///- {0} de memoria (RAM)
        ///- Dispositivo gráfico DirectX 9 con controlador WDDM, {1} de memoria de vídeo (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Vuestro configurazione:
        ///- {2} de memoria (RAM)
        ///- {3} de memoria de vídeo (VRAM).
        /// </summary>
        internal static string es_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("es_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error crítico. 
        ///
        ///Si estás viendo este mensaje por primera vez, reinicia la aplicación o reinstala el juego..
        /// </summary>
        internal static string es_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("es_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string es_ExitMenu {
            get {
                return ResourceManager.GetString("es_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidores de juego no disponibles..
        /// </summary>
        internal static string es_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("es_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidores de juego disponibles..
        /// </summary>
        internal static string es_GameServersStatusOk {
            get {
                return ResourceManager.GetString("es_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        internal static string es_Menu {
            get {
                return ResourceManager.GetString("es_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su tipo de NAT es: .
        /// </summary>
        internal static string es_NatType {
            get {
                return ResourceManager.GetString("es_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string es_No {
            get {
                return ResourceManager.GetString("es_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido actualizar el juego. 
        ///
        ///No es posible jugar conectado. 
        ///
        ///Si creas un perfil fuera de línea y actualizas el juego más tarde, no podrás jugar conectado con este perfil. 
        ///
        ///¿Quieres jugar desconectado?.
        /// </summary>
        internal static string es_OfflineMode {
            get {
                return ResourceManager.GetString("es_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string es_OK {
            get {
                return ResourceManager.GetString("es_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintento.
        /// </summary>
        internal static string es_Retry {
            get {
                return ResourceManager.GetString("es_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string es_SaveConfig {
            get {
                return ResourceManager.GetString("es_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string es_UnitBytes {
            get {
                return ResourceManager.GetString("es_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string es_UnitGigaBytes {
            get {
                return ResourceManager.GetString("es_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string es_UnitKiloBytes {
            get {
                return ResourceManager.GetString("es_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string es_UnitMegaBytes {
            get {
                return ResourceManager.GetString("es_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere ....
        /// </summary>
        internal static string es_Wait {
            get {
                return ResourceManager.GetString("es_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string es_Yes {
            get {
                return ResourceManager.GetString("es_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string ex_UnitTeraBytes {
            get {
                return ResourceManager.GetString("ex_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string fr_AudioLabel {
            get {
                return ResourceManager.GetString("fr_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string fr_Cancel {
            get {
                return ResourceManager.GetString("fr_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification des fichiers, veuillez patienter....
        /// </summary>
        internal static string fr_CheckingFiles {
            get {
                return ResourceManager.GetString("fr_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification du réseau, veuillez patienter....
        /// </summary>
        internal static string fr_CheckingNetwork {
            get {
                return ResourceManager.GetString("fr_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string fr_ConfigMenu {
            get {
                return ResourceManager.GetString("fr_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des erreurs se sont produites au cours de la mise à jour.
        ///S&apos;il vous plaît relancez la mise à jour.
        ///
        ///Si le problème persiste, contactez le support technique d&apos;Atari..
        /// </summary>
        internal static string fr_Error {
            get {
                return ResourceManager.GetString("fr_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas suffisamment d&apos;espace disque sur &quot;{0}&quot; pour installer les composants de la mise à jour.
        ///La mise à jour requiert un supplément de {1} d&apos;espace libre..
        /// </summary>
        internal static string fr_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("fr_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des erreurs se sont produites pendant le téléchargement de fichiers.
        ///S&apos;il vous plaît vérifiez votre connexion Internet, et de relancez la mise à jour.
        ///
        ///Si le problème persiste, contactez le support technique d&apos;Atari..
        /// </summary>
        internal static string fr_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("fr_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le jeu n&apos;est pas installé correctement sur ce système.
        ///S&apos;il vous plaît ré-installez le jeu à partir du programme d&apos;installation (DVD ou téléchargez l&apos;installateur).
        ///
        ///Si le problème persiste après installation du jeu, contactez le support technique d&apos;Atari..
        /// </summary>
        internal static string fr_ErrorGameInstall {
            get {
                return ResourceManager.GetString("fr_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des erreurs se sont produites lors de l&apos;installation des composants.
        ///S&apos;il vous plaît vérifiez vos autorisations d&apos;accès aux fichiers sur le répertoire &quot;{0}&quot;, et de relancez la mise à jour.
        ///
        ///Si le problème persiste, contactez le support technique d&apos;Atari..
        /// </summary>
        internal static string fr_ErrorInstallFile {
            get {
                return ResourceManager.GetString("fr_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé CD invalide.
        /// </summary>
        internal static string fr_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("fr_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre système ne répond pas aux exigences minimales.
        ///
        ///Configuration minimale requise :
        ///- {0} de mémoire système (RAM)
        ///- Carte vidéo compatible DirectX 9c avec pilote WDDM, {1} de mémoire vidéo (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Votre système:
        ///- {2} de mémoire système (RAM)
        ///- {3} de mémoire vidéo (VRAM).
        /// </summary>
        internal static string fr_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("fr_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur critique est survenue. 
        ///
        ///Si vous voyez ce message pour la première fois veuillez relancer l&apos;application sinon réinstallez le jeu..
        /// </summary>
        internal static string fr_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("fr_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string fr_ExitMenu {
            get {
                return ResourceManager.GetString("fr_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveurs de jeux indisponibles..
        /// </summary>
        internal static string fr_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("fr_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveurs de jeux disponibles..
        /// </summary>
        internal static string fr_GameServersStatusOk {
            get {
                return ResourceManager.GetString("fr_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string fr_Menu {
            get {
                return ResourceManager.GetString("fr_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre type de NAT est: .
        /// </summary>
        internal static string fr_NatType {
            get {
                return ResourceManager.GetString("fr_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string fr_No {
            get {
                return ResourceManager.GetString("fr_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de mettre à jour le jeu. 
        ///
        ///Voulez vous jouer hors ligne ?.
        /// </summary>
        internal static string fr_OfflineMode {
            get {
                return ResourceManager.GetString("fr_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string fr_OK {
            get {
                return ResourceManager.GetString("fr_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string fr_Retry {
            get {
                return ResourceManager.GetString("fr_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string fr_SaveConfig {
            get {
                return ResourceManager.GetString("fr_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string fr_UnitBytes {
            get {
                return ResourceManager.GetString("fr_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string fr_UnitGigaBytes {
            get {
                return ResourceManager.GetString("fr_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        internal static string fr_UnitKiloBytes {
            get {
                return ResourceManager.GetString("fr_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        internal static string fr_UnitMegaBytes {
            get {
                return ResourceManager.GetString("fr_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string fr_UnitTeraBytes {
            get {
                return ResourceManager.GetString("fr_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter....
        /// </summary>
        internal static string fr_Wait {
            get {
                return ResourceManager.GetString("fr_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string fr_Yes {
            get {
                return ResourceManager.GetString("fr_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string it_AudioLabel {
            get {
                return ResourceManager.GetString("it_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulli.
        /// </summary>
        internal static string it_Cancel {
            get {
                return ResourceManager.GetString("it_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica dei dati, si prega di attendere....
        /// </summary>
        internal static string it_CheckingFiles {
            get {
                return ResourceManager.GetString("it_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica di rete, si prega di attendere....
        /// </summary>
        internal static string it_CheckingNetwork {
            get {
                return ResourceManager.GetString("it_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurazione.
        /// </summary>
        internal static string it_ConfigMenu {
            get {
                return ResourceManager.GetString("it_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;aggiornamento.
        ///Si prega di riavviare l&apos;aggiornamento.
        ///
        ///Se il problema persiste, contattare il supporto tecnico di Atari..
        /// </summary>
        internal static string it_Error {
            get {
                return ResourceManager.GetString("it_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non c&apos;è abbastanza spazio su &quot;{0}&quot; per installare l&apos;aggiornamento.
        ///L&apos;aggiornamento richiede {1} di spazio libero..
        /// </summary>
        internal static string it_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("it_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante lo scaricamento dei dati.
        ///Si prega di verificare la connessione a Internet e riavviare l&apos;aggiornamento.
        ///
        ///Se il problema persiste, contattare il supporto tecnico di Atari..
        /// </summary>
        internal static string it_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("it_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il gioco non è stato installato correttamente sul sistema.
        ///Si prega di riprovare a installare il gioco tramite l&apos;installer (DVD o installer scaricato).
        ///
        ///Se il problema persiste, contattare il supporto tecnico di Atari..
        /// </summary>
        internal static string it_ErrorGameInstall {
            get {
                return ResourceManager.GetString("it_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;installazione dei componenti.
        ///Si prega di verificare i permessi per l&apos;accesso ai dati nell&apos;elenco &quot;{0}&quot;, in seguito riavviare l&apos;aggiornamento.
        ///
        ///Se il problema persiste, contattare il supporto tecnico di Atari..
        /// </summary>
        internal static string it_ErrorInstallFile {
            get {
                return ResourceManager.GetString("it_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Key non valido.
        /// </summary>
        internal static string it_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("it_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il sistema non soddisfa i requisiti minimi.
        ///
        ///Requisiti minimi:
        ///- {0} di memoria (RAM)
        ///- Scheda grafica DirectX 9 con driver WDDM, {1} di memoria video (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Vostro configuración
        ///- {2} di memoria (RAM)
        ///- {3} di memoria video (VRAM).
        /// </summary>
        internal static string it_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("it_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore critico. 
        ///
        ///Se è la prima volta che visualizzi questo messaggio, riavvia questa applicazione altrimenti reinstalla il gioco..
        /// </summary>
        internal static string it_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("it_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string it_ExitMenu {
            get {
                return ResourceManager.GetString("it_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server di gioco non disponibili..
        /// </summary>
        internal static string it_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("it_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server di gioco disponibili..
        /// </summary>
        internal static string it_GameServersStatusOk {
            get {
                return ResourceManager.GetString("it_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string it_Menu {
            get {
                return ResourceManager.GetString("it_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il vostro NAT è: .
        /// </summary>
        internal static string it_NatType {
            get {
                return ResourceManager.GetString("it_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string it_No {
            get {
                return ResourceManager.GetString("it_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile aggiornare il gioco. 
        ///
        ///Non potrai giocare online. 
        ///
        ///Creando un profilo non in linea e aggiornando in un secondo momento il gioco, sarai in grado di giocare online con questo profilo. 
        ///
        ///Desideri giocare non in linea?.
        /// </summary>
        internal static string it_OfflineMode {
            get {
                return ResourceManager.GetString("it_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string it_OK {
            get {
                return ResourceManager.GetString("it_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riprovi.
        /// </summary>
        internal static string it_Retry {
            get {
                return ResourceManager.GetString("it_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string it_SaveConfig {
            get {
                return ResourceManager.GetString("it_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string it_UnitBytes {
            get {
                return ResourceManager.GetString("it_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string it_UnitGigaBytes {
            get {
                return ResourceManager.GetString("it_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string it_UnitKiloBytes {
            get {
                return ResourceManager.GetString("it_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string it_UnitMegaBytes {
            get {
                return ResourceManager.GetString("it_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string it_UnitTeraBytes {
            get {
                return ResourceManager.GetString("it_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di attendere....
        /// </summary>
        internal static string it_Wait {
            get {
                return ResourceManager.GetString("it_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì.
        /// </summary>
        internal static string it_Yes {
            get {
                return ResourceManager.GetString("it_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーディオ.
        /// </summary>
        internal static string ja_AudioLabel {
            get {
                return ResourceManager.GetString("ja_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string ja_Cancel {
            get {
                return ResourceManager.GetString("ja_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルをチェックしています、お待ちください….
        /// </summary>
        internal static string ja_CheckingFiles {
            get {
                return ResourceManager.GetString("ja_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネットワークをチェックしています、お待ちください….
        /// </summary>
        internal static string ja_CheckingNetwork {
            get {
                return ResourceManager.GetString("ja_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンフィグ.
        /// </summary>
        internal static string ja_ConfigMenu {
            get {
                return ResourceManager.GetString("ja_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート中にエラーが発生しました。
        ///もう一度、アップデートを実行してください。
        ///
        ///問題が解決されない場合は、Atari テクニカルサポートまでご連絡ください。.
        /// </summary>
        internal static string ja_Error {
            get {
                return ResourceManager.GetString("ja_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;には、アップデートをインストールするために充分な空きスペースがありません。
        ///このアップデートには、{1}以上の空き容量が必要です。.
        /// </summary>
        internal static string ja_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("ja_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルのダウンロード中にエラーが発生しました。
        ///インターネットへの接続を確認し、もう一度、アップデートを実行してください。
        ///
        ///問題が解決されない場合は、Atari テクニカルサポートまでご連絡ください。.
        /// </summary>
        internal static string ja_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("ja_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームは正しくインストールされませんでした。
        ///インストーラー（DVD、またはダウンロードしたインストーラー）を使用して、もう一度インストールしてください。
        ///
        ///問題が解決されない場合は、Atari テクニカルサポートまでご連絡ください。.
        /// </summary>
        internal static string ja_ErrorGameInstall {
            get {
                return ResourceManager.GetString("ja_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンポーネントのインストール中にエラーが発生しました。
        ///&quot;{0}&quot;ディレクトリ上のファイルへのアクセス権を確認して、もう一度、アップデートを実行してください。
        ///
        ///問題が解決されない場合は、Atari テクニカルサポートまでご連絡ください。.
        /// </summary>
        internal static string ja_ErrorInstallFile {
            get {
                return ResourceManager.GetString("ja_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効なCDキー.
        /// </summary>
        internal static string ja_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("ja_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたのシステムは必要動作環境を満たしていません。
        ///
        ///必要動作環境：
        ///- システムメモリ（RAM） {0}
        ///- DirectX 9c WDDM対応のグラフィックボード、ビデオメモリ（VRAM） {1}、Shaders &quot;3.0&quot;
        ///
        ///あなたのシステム：
        ///- システムメモリ（RAM） {2}
        ///- ビデオメモリ（VRAM) {3}.
        /// </summary>
        internal static string ja_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("ja_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;重大なエラーが発生しました。
        ///
        ///このメッセージを初めてみた場合は、ゲームを再起動してください。そうでない場合はゲームを再インストールしてください&quot;.
        /// </summary>
        internal static string ja_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("ja_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string ja_ExitMenu {
            get {
                return ResourceManager.GetString("ja_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームサーバーは、ご利用いただけません。.
        /// </summary>
        internal static string ja_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("ja_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲームサーバーは、ご利用いただけます。.
        /// </summary>
        internal static string ja_GameServersStatusOk {
            get {
                return ResourceManager.GetString("ja_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メニュー.
        /// </summary>
        internal static string ja_Menu {
            get {
                return ResourceManager.GetString("ja_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたのNATタイプは：.
        /// </summary>
        internal static string ja_NatType {
            get {
                return ResourceManager.GetString("ja_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        internal static string ja_No {
            get {
                return ResourceManager.GetString("ja_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ゲームのアップデートに失敗しました。
        ///
        ///オンラインではゲームをプレイできません。
        ///
        ///オフラインプロフィールを作成し、後でゲームをアップデートする場合、このプロフィールはオンラインではプレイできなくなります。
        ///
        ///オフラインのままプレイをしますか？&quot;.
        /// </summary>
        internal static string ja_OfflineMode {
            get {
                return ResourceManager.GetString("ja_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 決定.
        /// </summary>
        internal static string ja_OK {
            get {
                return ResourceManager.GetString("ja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リトライ.
        /// </summary>
        internal static string ja_Retry {
            get {
                return ResourceManager.GetString("ja_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブ.
        /// </summary>
        internal static string ja_SaveConfig {
            get {
                return ResourceManager.GetString("ja_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ja_UnitBytes {
            get {
                return ResourceManager.GetString("ja_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string ja_UnitGigaBytes {
            get {
                return ResourceManager.GetString("ja_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string ja_UnitKiloBytes {
            get {
                return ResourceManager.GetString("ja_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string ja_UnitMegaBytes {
            get {
                return ResourceManager.GetString("ja_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string ja_UnitTeraBytes {
            get {
                return ResourceManager.GetString("ja_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お待ちください….
        /// </summary>
        internal static string ja_Wait {
            get {
                return ResourceManager.GetString("ja_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        internal static string ja_Yes {
            get {
                return ResourceManager.GetString("ja_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dźwięk.
        /// </summary>
        internal static string pl_AudioLabel {
            get {
                return ResourceManager.GetString("pl_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string pl_Cancel {
            get {
                return ResourceManager.GetString("pl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę czekać, trwa sprawdzanie plików....
        /// </summary>
        internal static string pl_CheckingFiles {
            get {
                return ResourceManager.GetString("pl_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę czekać, trwa sprawdzanie sieci....
        /// </summary>
        internal static string pl_CheckingNetwork {
            get {
                return ResourceManager.GetString("pl_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja.
        /// </summary>
        internal static string pl_ConfigMenu {
            get {
                return ResourceManager.GetString("pl_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas aktualizacji wystąpił błąd.
        ///Proszę ponownie uruchomić aktualizację.
        ///
        ///Jeśli problem będzie się powtarzał, proszę skontaktować się z działem pomocy technicznej Atari..
        /// </summary>
        internal static string pl_Error {
            get {
                return ResourceManager.GetString("pl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na dysku &quot;{0}&quot; brak wolnego miejsca na zainstalowanie aktualizacji.
        ///Aktualizacja wymaga {1} więcej wolnego miejsca..
        /// </summary>
        internal static string pl_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("pl_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas pobierania plików wystąpił błąd.
        ///Proszę sprawdzić połączenie internetowe i ponownie uruchomić aktualizację.
        ///
        ///Jeśli problem będzie się powtarzał, proszę skontaktować się z działem pomocy technicznej Atari..
        /// </summary>
        internal static string pl_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("pl_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra nie została prawidłowo zainstalowana.
        ///Proszę zainstalować grę ponownie za pomocą instalatora (z płyty DVD lub pobranym instalatorem).
        ///
        ///Jeśli problem będzie się powtarzał, proszę skontaktować się z działem pomocy technicznej Atari..
        /// </summary>
        internal static string pl_ErrorGameInstall {
            get {
                return ResourceManager.GetString("pl_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas sprawdzania składników wystąpił błąd.
        ///Proszę sprawdzić uprawnienia dostępu do plików w folderze &quot;{0}&quot;, po czym ponownie uruchomić aktualizację.
        ///
        ///Jeśli problem będzie się powtarzał, proszę skontaktować się z działem pomocy technicznej Atari..
        /// </summary>
        internal static string pl_ErrorInstallFile {
            get {
                return ResourceManager.GetString("pl_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny klucz CD.
        /// </summary>
        internal static string pl_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("pl_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System nie spełnia wymagań minimalnych.
        ///
        ///Wymagania minimalne:
        ///- {0} pamięci systemowej (RAM)
        ///- Karta graficzna zgodna z DirectX 9c ze sterownikami WDDM, {1} pamięci wideo (VRAM) i obsługą shaderów &quot;3.0&quot;
        ///
        ///Ten system:
        ///- {2} pamięci systemowej (RAM)
        ///- {3} pamięci wideo {VRAM}.
        /// </summary>
        internal static string pl_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("pl_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd krytyczny. 
        ///
        ///Jeśli widzisz ten komunikat po raz pierwszy, uruchom ponownie aplikację. W przeciwnym wypadku należy ponownie zainstalować grę..
        /// </summary>
        internal static string pl_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("pl_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjdź.
        /// </summary>
        internal static string pl_ExitMenu {
            get {
                return ResourceManager.GetString("pl_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwery gry niedostępne..
        /// </summary>
        internal static string pl_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("pl_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwery gry dostępne..
        /// </summary>
        internal static string pl_GameServersStatusOk {
            get {
                return ResourceManager.GetString("pl_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string pl_Menu {
            get {
                return ResourceManager.GetString("pl_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAT w tym systemie:.
        /// </summary>
        internal static string pl_NatType {
            get {
                return ResourceManager.GetString("pl_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string pl_No {
            get {
                return ResourceManager.GetString("pl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zaktualizować gry.
        ///
        ///Gra za pośrednictwem Internetu nie będzie możliwa.
        ///
        ///Jeśli utworzysz profil sieciowy w tym momencie, korzystając z niego gra za pośrednictwem Internetu nie będzie możliwa, nawet po aktualizacji.
        ///
        ///Czy chcesz grać w trybie offline?.
        /// </summary>
        internal static string pl_OfflineMode {
            get {
                return ResourceManager.GetString("pl_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string pl_OK {
            get {
                return ResourceManager.GetString("pl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponów.
        /// </summary>
        internal static string pl_Retry {
            get {
                return ResourceManager.GetString("pl_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string pl_SaveConfig {
            get {
                return ResourceManager.GetString("pl_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string pl_UnitBytes {
            get {
                return ResourceManager.GetString("pl_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string pl_UnitGigaBytes {
            get {
                return ResourceManager.GetString("pl_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string pl_UnitKiloBytes {
            get {
                return ResourceManager.GetString("pl_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string pl_UnitMegaBytes {
            get {
                return ResourceManager.GetString("pl_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string pl_UnitTeraBytes {
            get {
                return ResourceManager.GetString("pl_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosze czekac ....
        /// </summary>
        internal static string pl_Wait {
            get {
                return ResourceManager.GetString("pl_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string pl_Yes {
            get {
                return ResourceManager.GetString("pl_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио.
        /// </summary>
        internal static string ru_AudioLabel {
            get {
                return ResourceManager.GetString("ru_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string ru_Cancel {
            get {
                return ResourceManager.GetString("ru_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка файлов. Пожалуйста, подождите....
        /// </summary>
        internal static string ru_CheckingFiles {
            get {
                return ResourceManager.GetString("ru_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка сети. Пожалуйста, подождите....
        /// </summary>
        internal static string ru_CheckingNetwork {
            get {
                return ResourceManager.GetString("ru_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        internal static string ru_ConfigMenu {
            get {
                return ResourceManager.GetString("ru_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обновлении произошла ошибка.
        ///
        ///Начните обновление заново.
        ///
        ///Если проблема остается, свяжитесь со службой технической поддержки Atari..
        /// </summary>
        internal static string ru_Error {
            get {
                return ResourceManager.GetString("ru_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для установки обновления недостаточно места на &quot;{0}&quot;.
        ///Для обновления требуется еще {1} свободного места&quot;..
        /// </summary>
        internal static string ru_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("ru_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке файлов произошла ошибка.
        ///Проверьте интернет-соединение и начните обновление заново.
        ///
        ///Если проблема остается, свяжитесь со службой технической поддержки Atari..
        /// </summary>
        internal static string ru_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("ru_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра некорректно установлена в этой системе.
        ///Попытайтесь установить игру еще раз при помощи инсталлятора (скачанного или DVD-инсталлятора).
        ///
        ///
        ///Если проблема остается, свяжитесь со службой технической поддержки Atari..
        /// </summary>
        internal static string ru_ErrorGameInstall {
            get {
                return ResourceManager.GetString("ru_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При установке компонентов произошла ошибка.
        ///Убедитесь, что у вас есть полномочия, необходимые для доступа к файлам в директории &quot;{0}&quot;, и начните обновление еще раз.
        ///
        ///Если проблема остается, свяжитесь со службой технической поддержки Atari..
        /// </summary>
        internal static string ru_ErrorInstallFile {
            get {
                return ResourceManager.GetString("ru_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неверный CD-код.
        /// </summary>
        internal static string ru_ErrorKeyBanned {
            get {
                return ResourceManager.GetString("ru_ErrorKeyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша система не соответствует необходимым минимальным требованиям.
        ///
        ///
        ///
        ///Минимальные системные требования:
        ///- {0} оперативной памяти
        ///- DirectX 9c и WDDM, видеокарта с {1} памяти, Shaders &quot;3.0&quot;
        ///
        ///Ваша система:
        ///- {2} оперативной памяти
        ///- видеокарта с {3} памяти.
        /// </summary>
        internal static string ru_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("ru_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла критическая ошибка. 
        ///
        ///Если вы видите это сообщение.
        /// </summary>
        internal static string ru_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("ru_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string ru_ExitMenu {
            get {
                return ResourceManager.GetString("ru_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровые серверы недоступны..
        /// </summary>
        internal static string ru_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("ru_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровые серверы доступны..
        /// </summary>
        internal static string ru_GameServersStatusOk {
            get {
                return ResourceManager.GetString("ru_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        internal static string ru_Menu {
            get {
                return ResourceManager.GetString("ru_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш NAT:.
        /// </summary>
        internal static string ru_NatType {
            get {
                return ResourceManager.GetString("ru_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string ru_No {
            get {
                return ResourceManager.GetString("ru_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается обновить игру. 
        ///
        ///Вы не сможете играть по сети. 
        ///
        ///Если вы создадите профиль без подключения к сети и затем обновите игру, вы не сможете играть по сети, используя этот профиль. 
        ///
        ///Вы хотите сыграть без подключения к сети?.
        /// </summary>
        internal static string ru_OfflineMode {
            get {
                return ResourceManager.GetString("ru_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ru_OK {
            get {
                return ResourceManager.GetString("ru_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще раз.
        /// </summary>
        internal static string ru_Retry {
            get {
                return ResourceManager.GetString("ru_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение.
        /// </summary>
        internal static string ru_SaveConfig {
            get {
                return ResourceManager.GetString("ru_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to б.
        /// </summary>
        internal static string ru_UnitBytes {
            get {
                return ResourceManager.GetString("ru_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГБ.
        /// </summary>
        internal static string ru_UnitGigaBytes {
            get {
                return ResourceManager.GetString("ru_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кб.
        /// </summary>
        internal static string ru_UnitKiloBytes {
            get {
                return ResourceManager.GetString("ru_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МБ.
        /// </summary>
        internal static string ru_UnitMegaBytes {
            get {
                return ResourceManager.GetString("ru_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТБ.
        /// </summary>
        internal static string ru_UnitTeraBytes {
            get {
                return ResourceManager.GetString("ru_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите....
        /// </summary>
        internal static string ru_Wait {
            get {
                return ResourceManager.GetString("ru_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string ru_Yes {
            get {
                return ResourceManager.GetString("ru_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string zh_AudioLabel {
            get {
                return ResourceManager.GetString("zh_AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string zh_Cancel {
            get {
                return ResourceManager.GetString("zh_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking files, please wait....
        /// </summary>
        internal static string zh_CheckingFiles {
            get {
                return ResourceManager.GetString("zh_CheckingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking network, please wait....
        /// </summary>
        internal static string zh_CheckingNetwork {
            get {
                return ResourceManager.GetString("zh_CheckingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string zh_ConfigMenu {
            get {
                return ResourceManager.GetString("zh_ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating.
        ///Please restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string zh_Error {
            get {
                return ResourceManager.GetString("zh_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space on &quot;{0}&quot; to install the update.
        ///The update requires {1} more available space..
        /// </summary>
        internal static string zh_ErrorDiskSpace {
            get {
                return ResourceManager.GetString("zh_ErrorDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading files.
        ///Please check your Internet connection and restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string zh_ErrorDownloadFile {
            get {
                return ResourceManager.GetString("zh_ErrorDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game did not properly install on this system.
        ///Please try to install the game again using the installer (DVD or downloaded installer).
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string zh_ErrorGameInstall {
            get {
                return ResourceManager.GetString("zh_ErrorGameInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing components.
        ///Please check your permissions to access files on the directory &quot;{0}&quot;, then restart the update.
        ///
        ///If the problem persists, contact Atari technical support..
        /// </summary>
        internal static string zh_ErrorInstallFile {
            get {
                return ResourceManager.GetString("zh_ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system does not meet the minimum requirements.
        ///
        ///Minimum Requirements:
        ///- {0} of system memory (RAM)
        ///- DirectX 9c graphics device with WDDM, {1} of video memory (VRAM), Shaders &quot;3.0&quot;
        ///
        ///Your system:
        ///- {2} of system memory (RAM)
        ///- {3} of video memory (VRAM).
        /// </summary>
        internal static string zh_ErrorMinimumRequirements {
            get {
                return ResourceManager.GetString("zh_ErrorMinimumRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occurred. 
        ///
        ///If you are seeing this message for the first time please relaunch this application, otherwise reinstall the game..
        /// </summary>
        internal static string zh_ErrorRecoverFile {
            get {
                return ResourceManager.GetString("zh_ErrorRecoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string zh_ExitMenu {
            get {
                return ResourceManager.GetString("zh_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game servers unavailable..
        /// </summary>
        internal static string zh_GameServersStatusNOk {
            get {
                return ResourceManager.GetString("zh_GameServersStatusNOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game servers available..
        /// </summary>
        internal static string zh_GameServersStatusOk {
            get {
                return ResourceManager.GetString("zh_GameServersStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string zh_Menu {
            get {
                return ResourceManager.GetString("zh_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your NAT type is:.
        /// </summary>
        internal static string zh_NatType {
            get {
                return ResourceManager.GetString("zh_NatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string zh_No {
            get {
                return ResourceManager.GetString("zh_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the game. 
        ///
        ///You won&apos;t be able to play the game online. 
        ///
        ///If you create an offline profile and update the game later you won&apos;t be able to play online with this profile. 
        ///
        ///Do you want to play offline?.
        /// </summary>
        internal static string zh_OfflineMode {
            get {
                return ResourceManager.GetString("zh_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string zh_OK {
            get {
                return ResourceManager.GetString("zh_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string zh_Retry {
            get {
                return ResourceManager.GetString("zh_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string zh_SaveConfig {
            get {
                return ResourceManager.GetString("zh_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string zh_UnitBytes {
            get {
                return ResourceManager.GetString("zh_UnitBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string zh_UnitGigaBytes {
            get {
                return ResourceManager.GetString("zh_UnitGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string zh_UnitKiloBytes {
            get {
                return ResourceManager.GetString("zh_UnitKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string zh_UnitMegaBytes {
            get {
                return ResourceManager.GetString("zh_UnitMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string zh_UnitTeraBytes {
            get {
                return ResourceManager.GetString("zh_UnitTeraBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string zh_Wait {
            get {
                return ResourceManager.GetString("zh_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string zh_Yes {
            get {
                return ResourceManager.GetString("zh_Yes", resourceCulture);
            }
        }
    }
}
